### ISSUE TITLE
使用In的Bug

### ISSUE THREAD

**Issue by llxchen** [FeiniuBus/Linq.Dynamic#1]
> 
- 当实体字段为枚举时。动态查询使用枚举In操作，出错，错误提示：
  - No generic method 'Contains' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic.

**Comment by Lissbrict** [comment]
问题已处理 。 请升级版本

**Comment by Lissbrict** [comment]
09ef1d6ce0c015fc162a337e46966a24ba5b5736
